version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: capacity_planner_db
    environment:
      POSTGRES_DB: capacity_planner
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data: